In [1]:
import pandas as pd

df = pd.read_csv('Dataset_Q_Human_ChatGPT_Brook.csv')
df.head()

Question  \
0  what rights are gays actually being denied whi...   
1  why honey never expires  Selftext: edit what o...   
2  why is bandwidth measured in bits when everyth...   
3  why evolution is still considered a theory  Se...   
4  how should i teach a 5 year old what it means ...   

                                               Human  \
0  note that i m assuming you mean under us law t...   
1  food goes bad when tiny things grow in it in o...   
2  actually it is because the focus of the two te...   
3  a scientific theory is not simply a guess that...   
4  i think its enough to work on his empathy in t...   

                                             ChatGPT  
0  It's important to note that as of my last know...  
1                                                     
2   Bandwidth is typically measured in bits rathe...  
3                                                     
4   Teaching a 5-year-old what it means to be hum...

In [2]:
subdf = df.loc[df['ChatGPT'].str.len()>1,:]
print(len(subdf))

100


In [3]:
import re
subdf['ChatGPT'] = subdf['ChatGPT'].apply(lambda x:re.sub(r'\W+',' ',x.lower()))
#subdf.to_csv('Clean_100.csv', index=False) #Because I have already created the file 

C:\Users\manikl\AppData\Local\Temp/ipykernel_21744/3156025427.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subdf['ChatGPT'] = subdf['ChatGPT'].apply(lambda x:re.sub(r'\W+',' ',x.lower()))


In [4]:
!python -m spacy download en_core_web_md

2023-10-27 11:40:05.049192: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-10-27 11:40:05.049384: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-10-27 11:40:10.694044: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2023-10-27 11:40:10.694437: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
2023-10-27 11:40:10.704647: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: Manikl-TB15
2023-10-27 11:40:10.704793: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: Manikl-TB15


[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_md')


In [5]:
!pip install -U sentence-transformers

In [6]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('distilbert-base-nli-mean-tokens')

In [7]:
#from sentence_transformers import SentenceTransformer
#model = SentenceTransformer('distilbert-base-nli-mean-tokens')
sentences = ['This framework generates embeddings for each input sentence',
    'Sentences are passed as a list of string.', 
    'The quick brown fox jumps over the lazy dog.']
sentence_embeddings = model.encode(sentences)
embeds=[]
for sentence, embedding in zip(sentences, sentence_embeddings):
    print("Sentence:", sentence)
    print("Embedding:", embedding)
    embeds.append(embedding)
    print("")

print(len(embeds))

Sentence: This framework generates embeddings for each input sentence
Embedding: [-4.99964207e-01  2.00928763e-01  4.79733527e-01 -5.45866415e-02
 -3.20265293e-01 -1.18349604e-01  1.19828200e+00  6.53363466e-02
  2.56168365e-01 -6.80206299e-01 -2.65210778e-01  9.71701443e-02
 -2.19010815e-01 -4.23998415e-01 -1.44659858e-02 -2.27257699e-01
 -3.66329730e-01  4.29631211e-02 -2.45088786e-01 -1.15445685e+00
  1.01486611e+00 -4.86818165e-01 -3.97847503e-01  1.33469319e+00
  7.27641225e-01 -2.61947215e-01  9.74691808e-01  3.20754409e-01
  9.10776705e-02 -1.66288450e-01 -1.71081528e-01 -2.45369017e-01
 -2.78276384e-01  5.85470617e-01  2.47854099e-01 -5.16083360e-01
  8.40410888e-01 -1.11888111e+00 -1.02041519e+00 -2.46360317e-01
  3.75287175e-01 -4.89003628e-01  5.48438728e-01 -1.94785655e-01
 -3.49307030e-01  1.85083132e-02 -3.58544290e-02  3.46165359e-01
 -1.75415742e+00 -3.57941568e-01 -1.20965266e+00  2.49583498e-01
  7.49337494e-01 -3.55311841e-01 -5.63870668e-01 -8.27796385e-02
  2.31488

In [8]:
import pandas as pd

df = pd.read_csv('Clean_100.csv')
df.head()

Question  \
0  what rights are gays actually being denied whi...   
1  why is bandwidth measured in bits when everyth...   
2  how should i teach a 5 year old what it means ...   
3  what is the hiv cure  Selftext: i think that a...   
4  how can i best help and encourage my tech adva...   

                                               Human  \
0  note that i m assuming you mean under us law t...   
1  actually it is because the focus of the two te...   
2  i think its enough to work on his empathy in t...   
3  this will have to be like you re five because ...   
4  as someone that learned design then programmin...   

                                             ChatGPT Similarity_Amish  \
0  it s important to note that as of my last know...               NS   
1   bandwidth is typically measured in bits rathe...               NS   
2   teaching a 5 year old what it means to be hum...                S   
3   as of my last knowledge update in september 2...               NS   
4   it s great that you want to support and encou...               NS   

  Similarity_Brook  Matching  
0                S         0  
1                S         0  
2                S         1  
3               NS         1  
4                S         0

In [9]:
human = df['Human'].tolist()
chatgpt = df['ChatGPT'].tolist()

human_embeddings = model.encode(human)
human_embeds=[]
for sentence, embedding in zip(human, human_embeddings):
    human_embeds.append(embedding)
    print("")

print(len(human_embeds))


chatgpt_embeddings = model.encode(chatgpt)
chatgpt_embeds=[]
for sentence, embedding in zip(chatgpt, chatgpt_embeddings):
    chatgpt_embeds.append(embedding)
    print("")

print(len(chatgpt_embeds))





































































































100




































































































100


### Cosine Similarity between the embeddings 

In [10]:
from sklearn.metrics.pairwise import euclidean_distances

matrix = euclidean_distances(human_embeds, chatgpt_embeds)

print(matrix.mean())
print(matrix.std())

15.95555
1.7773885


In [12]:
len(matrix)

100

In [18]:
mats = []
for i in range(100):
    mats.append(matrix[i][i])
    print(matrix[i][i])
    
print(mats)

9.167728
12.638143
12.380526
10.493092
12.46833
6.2889504
12.221087
8.19935
11.162459
12.357384
13.86691
9.174655
13.401849
9.137073
8.588626
11.525461
10.908342
12.69716
16.416016
11.065987
12.639732
16.404654
13.5895405
15.097727
13.33484
10.261738
12.274846
13.357373
10.665237
15.037121
12.9794855
15.649995
11.924316
12.156506
12.617847
8.106573
13.975483
9.9845
13.340788
12.554941
18.34817
17.648123
9.498836
8.376136
12.849975
11.68564
8.801833
12.825861
9.500587
10.827537
10.522548
11.758214
13.140726
11.989793
13.546171
11.311877
15.067034
13.30913
13.583829
9.035973
12.2318535
13.082686
14.0605545
10.725475
9.967383
11.248299
12.031292
11.174582
10.65322
7.7208567
13.722255
6.864702
8.390586
20.142155
7.7838936
12.843847
10.870243
13.10541
10.1221
12.132595
9.00355
11.313011
12.233352
16.493023
9.812831
15.5579605
10.655409
15.924978
13.102178
14.546044
16.243185
11.670247
9.647979
10.674945
10.962505
9.197104
10.495983
9.776275
13.966759
15.183565
[9.167728, 12.638143, 12.38052

In [16]:
from sklearn.metrics.pairwise import cosine_similarity

vals = cosine_similarity(human_embeds, chatgpt_embeds)
print(vals)

print(vals.mean())
print(vals.std())

[[0.8193028  0.40112847 0.3842872  ... 0.41562957 0.3770343  0.44479042]
 [0.4824165  0.6556748  0.46393478 ... 0.59376466 0.64903504 0.6225538 ]
 [0.49470577 0.5651744  0.67860246 ... 0.45368814 0.6162896  0.45014203]
 ...
 [0.56259537 0.30345643 0.46850997 ... 0.8110448  0.5351547  0.58692324]
 [0.4290455  0.55023175 0.4070105  ... 0.38587362 0.6034369  0.4598443 ]
 [0.49610806 0.506796   0.41427344 ... 0.5247463  0.39004457 0.52771276]]
0.47357413
0.107413955


In [21]:
mats2 = []
for i in range(100):
    mats2.append(vals[i][i])
    print(vals[i][i])
    
print(mats2)
print(len(mats2))

0.8193028
0.6556748
0.67860246
0.77065885
0.68513584
0.9193416
0.67619133
0.85524106
0.7178004
0.68028486
0.5933498
0.83367085
0.61655104
0.8337636
0.84967995
0.7272867
0.7523613
0.66009176
0.4622299
0.73025334
0.6623845
0.4460323
0.6208924
0.56535125
0.64190376
0.7845826
0.68176746
0.6312963
0.7709216
0.5725113
0.66467416
0.48711088
0.71730083
0.70326966
0.66589046
0.8646171
0.59048975
0.7875259
0.6551893
0.68534076
0.34826365
0.41281936
0.8091091
0.85698485
0.6795293
0.72761154
0.85268265
0.6348605
0.81869113
0.7684914
0.77304673
0.70934284
0.6438291
0.68938327
0.6401143
0.73631096
0.55366355
0.6265515
0.6434428
0.83621776
0.67966616
0.6392777
0.6066407
0.76826614
0.7950994
0.72796416
0.669597
0.75794256
0.76050645
0.88422495
0.62225497
0.9092405
0.8656447
0.2473988
0.87645113
0.6538495
0.7545253
0.64839685
0.78670263
0.7125449
0.82946706
0.7349607
0.668002
0.41193736
0.8040209
0.5144928
0.7686143
0.49737525
0.6499134
0.56358546
0.46148482
0.72527075
0.7928419
0.7771697
0.78244555
0.

In [22]:
import numpy as np

arr = np.array([0,0.25,0.5,0.75,1.1])
newvals = np.digitize(mats2,arr)
print(len(newvals))
print(newvals)

100
[4 3 3 4 3 4 3 4 3 3 3 4 3 4 4 3 4 3 2 3 3 2 3 3 3 4 3 3 4 3 3 2 3 3 3 4 3
 4 3 3 2 2 4 4 3 3 4 3 4 4 4 3 3 3 3 3 3 3 3 4 3 3 3 4 4 3 3 4 4 4 3 4 4 1
 4 3 4 3 4 3 4 3 3 2 4 3 4 2 3 3 2 3 4 4 4 4 3 4 3 3]


In [23]:
newvals = list(newvals)
print(newvals.count(4))
print(newvals.count(3))
print(newvals.count(2))
print(newvals.count(1))

37
54
8
1


In [25]:
np.array(mats2).mean()

0.693461